### Deletar
DELETE http://localhost:8080/produtos/xRZmlGDSd0lbakMVCO6o

### GET dos produtos
GET http://localhost:8080/produtos/

### GET dos clientes
GET http://localhost:8080/clientes/

### Post do PDV
POST http://localhost:8080/pdv
Content-Type: application/json

{
  "clienteId": "em1wQmENvUb8OKtk8ri4",
  "produtos": ["B28RgyjXgKHK335FjL7x","ELUEQC7EDBo8GGK1Kq2e" ],
  "valorPago": 40.00
}



